### ISSUE TITLE
Shadow root?

### ISSUE THREAD

**Issue by ghost** [amnweb/blur-menu-vscode#3]
is the right click context menu backdrop filter broken due to vscode now using a shadow root to draw it?

No blur in context menu 

![image](https://github.com/amnweb/blur-menu-vscode/assets/83620116/5a621493-fc4c-44ae-9b77-15eaf30cbd07)

But blur in other menus

![image](https://github.com/amnweb/blur-menu-vscode/assets/83620116/a310d430-6ec2-4088-847e-c0d517a16c3d)

**Comment by amnweb** [comment]
VSCode version?
Did you try to reenable Extension ?

**Comment by ghost** [comment]
I spent a good 3 hours trying to target .monaco-scrollable-element for the shadow root host for the right click context menu, tried everything. Am on Insiders January 1.86

**Comment by CreationStory** [comment]
I might be wrong here but in your extension I see it appends with javascript the lines needed for the blur frosted glass effect, but I want to ask you, have you tried your own extension on Insiders build? I would really like to get ot the bottom of why I cant style inside the shadow root host I've tried part, deep, js path, I just cant get the right click context menu to get customized in any way

**Comment by amnweb** [comment]
Yes, there is a problem in Insiders 1.86, but I found a solution. I'll try to fix this problem today or tomorrow and update the extension.

 _Insiders 1.86 installed for test_ 
 
![Screenshot 2024-01-09 154632](https://github.com/amnweb/blur-menu-vscode/assets/16545063/80a93c1c-818f-4e2b-a911-18ccb12307aa)

**Comment by amnweb** [comment]
@CreationStory please update the extension and let me know if it's working.

**Comment by CreationStory** [comment]
Working wonderfully thanks lad. also check out my vscode it looks gang ting dun it


![image](https://github.com/amnweb/blur-menu-vscode/assets/83620116/61734439-1a05-43ee-951b-440506fd14c1)

![image](https://github.com/amnweb/blur-menu-vscode/assets/83620116/7dad4dce-76d7-408f-a36c-b72d6a29932d)

**Comment by CreationStory** [comment]
Also can I just say WOW congratulations on defeating this shadow root problem. Can't believe .shadow-root-host::part(menu)::after{z-index:-1;content: was the one!

I had a crazy css selector nearly working last night 
![image](https://github.com/amnweb/blur-menu-vscode/assets/83620116/7e9fc916-bce8-463b-97f0-0e8fe5ac31fc)
🤣

**Comment by amnweb** [comment]
Yes, `part,menu` was a problem, but I have now included regax in the extension and it should work fine in the future. I have also switched to sha256 for the checksum, so I hope there will be no more problems

**Comment by CreationStory** [comment]
The problem was from the shadow root host being drawn with two of its own inline style files, but you have now fully overridden them. gg

**Comment by dashubhams** [comment]
@amnweb Happening Again! As soon as I updated the VS Code. It was working on the previous version.

Platform Details:
![image](https://github.com/amnweb/blur-menu-vscode/assets/111336675/df90c256-23d9-43b5-ac8b-49d5ea112456)

Issue: Blur is working fine on all the menus but editor 
![image](https://github.com/amnweb/blur-menu-vscode/assets/111336675/a5b03ff0-d1d7-4db7-8adb-51a7e547737c)
