### ISSUE TITLE
Command 'Blur menu - enable blur' resulted in an error

### ISSUE THREAD

**Issue by Krystian-Matusiak** [amnweb/blur-menu-vscode#4]
Hi I have the following problem after applying enable animation:
![image](https://github.com/amnweb/blur-menu-vscode/assets/62670083/3ae8f27b-9af3-4c51-87a7-785aa52432fd)

**Comment by amnweb** [comment]
To ensure the extension works, allow VSCode to modify itself by fixing read-only code files and permission issues. `sudo chown -R $(whoami) <path>` example:

**Linux** 
`sudo chown -R $(whoami) /usr/share/code`

**MacOS**
`sudo chown -R $(whoami) $(which code)`

Change path based on your installation and distro.
