### ISSUE TITLE
Editor Menu Not Blurred

### ISSUE THREAD

**Issue by dashubhams** [amnweb/blur-menu-vscode#5]
Happening Again! As soon as I updated the VS Code, Editor Menu was no longer blurred. Tried reloading, re-enabling etc. It was working in the previous version.

Platform Details:
![image](https://github.com/amnweb/blur-menu-vscode/assets/111336675/9033d215-86d4-48ba-9167-b5688c428529)

Issue: Blur is working fine on all the menus but editor
![image](https://github.com/amnweb/blur-menu-vscode/assets/111336675/8c087319-4f92-4107-aff6-bea0509e403e)

Looks like a duplicate of #3

**Comment by amnweb** [comment]
I will check this.

**Comment by amnweb** [comment]
Please update extension and let me know if issue fixed

**Comment by dashubhams** [comment]
It's fixed. Thanks.
