### ISSUE TITLE
Doesn't Blur Behind File Changer

### ISSUE THREAD

**Issue by XxDraggy** [amnweb/blur-menu-vscode#7]
Hi!
as said in the title the extension doesn't blur behind the file changer even tho it changes the color of it:

![Screenshot 2024-08-05 144210](https://github.com/user-attachments/assets/dbd4c354-d696-4580-9135-73afc140fc63)

Edit: This applies to the message background aswell:

![Screenshot 2024-08-05 160013](https://github.com/user-attachments/assets/94496168-6f39-481a-8df2-7096cc6e628d)

**Comment by amnweb** [comment]
I can just recommend you to switch on https://github.com/amnweb/SpaceBox-UI-Enhancer where you can import your own style and enable blur where you want.
